# composition for m2

version: '3'
networks:
    default:
        external:
           name: magento
services:
    nginx: 
      image: nginx:alpine
      container_name: ${NGINX_CONTAINER}
      restart: always
      volumes:
#        - 'nfsmount:/var/www/html'
        - ./www:/var/www/html
        - ./etc/nginx/magento-nginx.conf:/etc/nginx/magento-nginx.conf
        - ./etc/nginx/certs:/etc/nginx/certs
        - ./etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template
        - ./etc/nginx/conf.d/proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf
        - ./etc/nginx/scripts:/etc/nginx/scripts
      expose:
        - "80"
        - "443"
      environment:
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        VIRTUAL_PROTO: ${VIRTUAL_PROTO}
        VIRTUAL_PORT: ${VIRTUAL_PORT}
        PHP_CONTAINER: ${PHP_CONTAINER}
      depends_on:
        - php
      command: /bin/sh /etc/nginx/scripts/start-nginx.sh
    php: 
      image: magento/php${PHP_VERSION}
      container_name: ${PHP_CONTAINER}
      restart: always
      ports: 
        - "${LOCAL_PORT}:9000"
      volumes:
#        - 'nfsmount:/var/www/html'
        - ./www:/var/www/html
        - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
#volumes:
#    nfsmount:
#      driver: local
#      driver_opts:
#        type: nfs
#        o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#        device: ":/System/Volumes/Data/${PWD}/www"
