# composition for m2

version: '3'
networks:
    default:
        external:
           name: magento
services:
    nginx: 
      image: nginx:alpine
      container_name: ${NGINX_CONTAINER}
      restart: always
      volumes:
        - ./www:/var/www/html
        - ./etc/nginx/magento-nginx.conf:/etc/nginx/magento-nginx.conf
        - ./etc/nginx/certs:/etc/nginx/certs:ro
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
      expose:
        - "80"
        - "443"
      environment:
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        VIRTUAL_PROTO: ${VIRTUAL_PROTO}
        VIRTUAL_PORT: ${VIRTUAL_PORT}
      restart: always
      depends_on:
        - php
    php: 
      image: magento/php${PHP_VERSION}
      container_name: ${PHP_CONTAINER}
      restart: always
      user: www-data
      ports: 
        - "${LOCAL_PORT}:9000"
      volumes:
        - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./www:/var/www/html
