# extensions-store  m2

version: '3'
networks:
    default:
        external:
           name: magento
services:
    nginx: 
      image: nginx:alpine
      container_name: ${NGINX_CONTAINER}
      restart: always
      volumes:
        - "./www:/var/www/html"
        - "./etc/ssl:/etc/ssl"
        - "./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
        - "./etc/nginx/magento-nginx.conf:/etc/nginx/magento-nginx.conf"
      expose:
        - "80"
      environment:
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      restart: always
      depends_on:
        - php
    php: 
      image: magento/php
      container_name: ${PHP_CONTAINER}
      restart: always
      user: www-data
      ports: 
        - "${LOCAL_PORT}:9000"
      volumes:
        - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        - "./www:/var/www/html" 
